resources:
- name: repo
  type: git
  source:
    uri: https://github.com/ggrammar/concourse-sample.git

jobs:
- name: hello-world-job
  # Concourse will run steps (plan members) in the order that they are listed.
  # A step is a single container running on a Concourse worker. Each step runs in its own container.
  plan:
  - get: repo
    trigger: true # trigger this job when the 'repo' resource emits new versions 
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs:
      - name: repo
      run:
        path: cat
        args: ["repo/README.md"]
